### ISSUE TITLE
Deploy 2048 to Heroku

### ISSUE THREAD

**Issue by harryworld** [wdi-hk-sep-2014/notes#11]
We should have a session doing this.

**Comment by naterexw** [comment]
Add instructions for wrapping front-end app inside PHP code to be able to deploy on Heroku

**Comment by f3r** [comment]
@naterex php? :-1:

**Comment by naterexw** [comment]
I agree @f3r , but I believe its necessary to wrap an app with only HTML/CSS/JS inside PHP syntax to be able to deploy on Heroku

**Comment by harryworld** [comment]
http://www.lemiffe.com/how-to-deploy-a-static-page-to-heroku-the-easy-way/
