### ISSUE TITLE
sublime user settings

### ISSUE THREAD

**Issue by naterexw** [wdi-hk-sep-2014/notes#12]
{
"bold_folder_labels": true,
"caret_extra_bottom": 0,
"caret_extra_top": 0,
"caret_extra_width": 2,
"caret_style": "phase",
"create_window_at_startup": false,
"cross_width": 12,
"default_encoding": "UTF-8",
"fade_fold_buttons": false,
"font_options": "subpixel_antialias",
"font_size": 13,
"highlight_active_indent_guide": true,
"highlight_line": true,
"highlight_modified_tabs": true,
"hot_exit": true,
"ignored_packages":
[
"FileDiffs",
"Markdown",
"Vintage"
],
"remember_open_files": true,
"shift_tab_unindent": true,
"show_cross": true,
"show_full_path": true,
"show_multiple_cross": true,
"tab_size": 2,
"translate_tabs_to_spaces": true,
"trim_trailing_white_space_on_save": true,
"use_simple_full_screen": false,
"vintage_start_in_command_mode": true
}

**Comment by titaniumtails** [comment]
{
    "bold_folder_labels": true,
    "color_scheme": "Packages/User/3024_Day (SL).tmTheme",
    "font_size": 13,
    "ignored_packages":
    [
        "Vintage",
        "Markdown"
    ],
    "tab_size": 2,
    "theme": "El Capitan.sublime-theme",
    "translate_tabs_to_spaces": true
}
