### ISSUE TITLE
[Coffee Script] How to Create a Function and Call a Function

### ISSUE THREAD

**Issue by AeroWong** [wdi-hk-sep-2014/notes#3]
4 basic elements for create a function in CoffeeScript
- variable name (register)
- thin arrow -> as function
- result
- arguments (optional)

2 basic elements for call a function
- variable name (use it)
- parentheses to call it

**Comment by harryworld** [comment]
Thanks, will add it to function

**Comment by harryworld** [comment]
Reference to here
https://github.com/wdi-hk-sep-2014/notes/blob/master/phase-1%2Flessons%2F1st-pass%2F07-functions.md#how-to-define-function
