### ISSUE TITLE
Can we use range in for loop with index?

### ISSUE THREAD

**Issue by harryworld** [wdi-hk-sep-2014/notes#8]
As question, like this

```
for elem, index in [0..10]
  console.log index
```

**Comment by harryworld** [comment]
Check the discussion here:
https://github.com/jashkenas/coffeescript/issues/2586

**Comment by domtkho** [comment]
It seems like you can use a range in a for loop if you put a () around the range?

/code for elem, index in ([1..10])
  console.log elem

**Comment by harryworld** [comment]
Yes, that's the case for now @domtkho 
even though people from Python world says it should be easier, because they can do it in Python
